export const simulateData = [
  {
    name: "Cereal",
    link: "",
    servings: undefined,
    prepTimeMin: undefined,
    ingredients: [
      { name: "soda", quantity: "1", units: undefined },
      { name: "milk", quantity: "12", units: "fl/oz" },
      { name: "cereal", quantity: "1", units: "cup" },
    ],
    multiplier: 1,
    cost: undefined,
  },
  {
    name: "Biscuit and Gravy w/ Toast",
    link: "",
    servings: 4,
    prepTimeMin: 90,
    ingredients: [
      { name: "soda", quantity: "1", units: undefined },
      { name: "buns", quantity: "2", units: undefined },
    ],
    multiplier: 1,
    cost: 32,
  },
  {
    name: "Burger",
    link: "",
    servings: 4,
    prepTimeMin: 25,
    ingredients: [
      { name: "soda", quantity: "1", units: undefined },
      { name: "buns", quantity: "1", units: undefined },
      { name: "tomato", quantity: "2", units: undefined },
      { name: "patty", quantity: "2", units: "lbs" },
    ],
    multiplier: 1,
    cost: 14,
  },
  {
    name: "Fried Chicken",
    link: "",
    servings: 6,
    prepTimeMin: 50,
    ingredients: [
      { name: "soda", quantity: "1", units: undefined },
      { name: "milk", quantity: "12", units: "fl/oz" },
      { name: "Chicken", quantity: "3", units: "lbs" },
    ],
    multiplier: 1,
    cost: 30,
  },
  {
    name: "Soup",
    link: "",
    servings: 3,
    prepTimeMin: 20,
    ingredients: [
      { name: "soda", quantity: "1", units: undefined },
      { name: "buns", quantity: "2", units: undefined },
    ],
    multiplier: 1,
    cost: 23,
  },
  {
    name: "Fried Rice",
    link: "",
    servings: 4,
    prepTimeMin: 25,
    ingredients: [
      { name: "oil", quantity: "1", units: "tbsp" },
      { name: "Rice", quantity: "2", units: "lbs" },
      { name: "soda", quantity: "1", units: undefined },
    ],
    multiplier: 1,
    cost: 14,
  },
  {
    name: "Burrito",
    link: "",
    servings: 3,
    prepTimeMin: 20,
    ingredients: [
      { name: "meat", quantity: "1", units: "lbs" },
      { name: "shell", quantity: "2", units: undefined },
      { name: "soda", quantity: "1", units: undefined },
    ],
    multiplier: 1,
    cost: 23,
  },
  {
    name: "Eggs",
    link: "",
    servings: 4,
    prepTimeMin: 25,
    ingredients: [
      { name: "Eggs", quantity: "1", units: undefined },
      { name: "Rice", quantity: "2", units: "lbs" },
      { name: "soda", quantity: "1", units: undefined },
    ],
    multiplier: 1,
    cost: 14,
  },
];
